# Training configs.

architecture:
  desc: The architecture of the model.
  value: MobileNetV2

batch_size:
  desc: Size of each mini-batch for training.
  value: 8

dataset_seed:
  desc: Random seed for dataset splitting.
  value: 42

dropout:
  desc: Dropout rate for the model.
  value: 0.3

epochs:
  desc: Number of epochs to train the model.
  value: 30

image_size:
  desc: Input image size for the model.
  value:
    - 224
    - 224
    - 3

learning_rate:
  desc: Learning rate for the optimizer.
  value: 0.001

patience:
  desc: Number of epochs with no improvement after which training will be stopped.
  value: 6

validation_batch_size:
  desc: Size of each mini-batch for validation.
  value: 4
